import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
const root = path.resolve(import.meta.dirname, "../../..");
const dest = path.resolve(import.meta.dirname, "../.generated");
const require = createRequire(path.join(root, "package.json"));
const postcss = require("postcss");
await fs.mkdir(dest, { recursive: true });

// Generate render-only controlled versions of the actual game tables.
// Their markup, labels, legality checks and asset paths remain the app's own.
for (const name of ["DoudizhuTable", "MahjongTable", "XiangqiBoard"]) {
  let source = await fs.readFile(
    path.join(root, "src/components", name + ".tsx"),
    "utf8",
  );
  source = source.replaceAll("../../shared/", "../../../shared/");
  source = source.replace(
    /from "\.\/([^"\n]+)"/g,
    'from "../../../src/components/$1"',
  );
  const isCards = name === "DoudizhuTable";
  const value = isCards ? "[]" : "null";
  const type = isCards ? "number[]" : "number | null";
  source = source.replace("  match,", `  match,\n  replaySelected = ${value},`);
  source = source.replace("  match:", `  replaySelected?: ${type};\n  match:`);
  if (name === "XiangqiBoard") {
    source = source.replace(
      /const selected =[\s\S]*?const destinations =/,
      "const selected = replaySelected;\n  const destinations =",
    );
  } else {
    source = source.replace(
      "[selected, setSelected]",
      "[_localSelected, setSelected]",
    );
    source = source.replace(
      "  const active =",
      "  const selected = replaySelected;\n  const active =",
    );
    if (name === "MahjongTable") {
      // The app's smooth scroll uses wall time. The video drives it by frame.
      source = source.replace(
        /  useEffect\(\(\) => \{\n    if \(selected !== null\)[\s\S]*?\}, \[selected\]\);/,
        "",
      );
      source = source.replace(
        "key={i}\n                      className=",
        "key={i}\n                      data-choice={o.choice}\n                      className=",
      );
    }
  }
  await fs.writeFile(
    path.join(dest, name + ".tsx"),
    "// Generated by scripts/prepare.mjs; do not edit.\n" + source,
  );
}

// Remotion's output is 1080 px wide, while the filmed app viewport is 450 px.
// Resolve the existing mobile media queries for that viewport, before scaling.
function matches(query) {
  return query.split(",").some((part) => {
    if (/prefers-reduced-motion:\s*reduce/.test(part)) return false;
    let valid = true;
    for (const m of part.matchAll(
      /\((min|max)-(width|height):\s*([\d.]+)px\)/g,
    )) {
      const size = m[2] === "width" ? 450 : 800;
      valid &&= m[1] === "min" ? size >= +m[3] : size <= +m[3];
    }
    if (/orientation:\s*landscape/.test(part)) valid = false;
    return valid;
  });
}
const names = [
  "styles",
  "toolbar",
  "account",
  "chat",
  "gomoku",
  "doudizhu",
  "xiangqi",
  "mobile",
  "mahjong",
];
let css = "";
for (const name of names) {
  const tree = postcss.parse(
    await fs.readFile(path.join(root, "src", name + ".css"), "utf8"),
  );
  tree.walkAtRules("media", (rule) => {
    if (matches(rule.params)) rule.replaceWith(...rule.nodes);
    else rule.remove();
  });
  tree.walkAtRules("import", (rule) => rule.remove());
  // Assets are loaded from Remotion's public server, never by webpack's resolver.
  tree.walkDecls((decl) => {
    decl.value = decl.value.replace(
      /url\(["']?(\/[^"')]+)["']?\)/g,
      (_, url) => `url("${url}")`,
    );
  });
  css += `\n/* ${name}.css at 450 x 800 */\n` + tree.toString();
}
css +=
  "\n" +
  (await fs.readFile(
    path.join(root, "public/assets/playing-cards-v2/card.css"),
    "utf8",
  ));
css +=
  "\n" +
  (await fs.readFile(
    path.join(root, "public/assets/mahjong-v1/tile.css"),
    "utf8",
  ));
// These two asset styles use directory-relative URLs in the app.
css = css.replace(/url\(["']?(?!\/|data:)([^"')]+)["']?\)/g, (_, value) => {
  const dir = value.startsWith("tile-") ? "mahjong-v1" : "playing-cards-v2";
  return `url("/assets/${dir}/${value}")`;
});
await fs.writeFile(
  path.join(dest, "app-css.ts"),
  "export default " + JSON.stringify(css) + ";\n",
);
const assets = [];
async function scan(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) await scan(file);
    else if (/\.(svg|webp)$/.test(file))
      assets.push("/" + path.relative(path.join(root, "public"), file));
  }
}
await scan(path.join(root, "public/assets"));
await scan(path.join(root, "public/textures"));
await fs.writeFile(
  path.join(dest, "assets.ts"),
  "export default " + JSON.stringify(assets) + ";\n",
);
await fs.mkdir(path.join(dest, "public/promo-audio"), { recursive: true });
await fs.cp(
  path.join(root, "public/assets"),
  path.join(dest, "public/assets"),
  { recursive: true },
);
await fs.cp(
  path.join(root, "public/textures"),
  path.join(dest, "public/textures"),
  { recursive: true },
);
console.log(
  "Prepared original UI components, mobile styles and " +
    assets.length +
    " local assets.",
);
